words = [
    "bdelete",
    "bufnr",
    "enew",
    "expandtab",
    "fileformat",
    "keybinds",
    "listchars",
    "liststyle",
    "mapleader",
    "netrw",
    "noremap",
    "relativenumber",
    "setlocal",
    "shiftwidth",
    "softtabstop",
    "tabclose",
    "tabedit",
    "tabn",
    "tabstop",
]
